# Form implementation generated from reading ui file 'ventanamapa.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QComboBox {\n"
"    background-color: #2b2b2b;\n"
"    color: white;\n"
"    border: 1px solid #555;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #2b2b2b;\n"
"    color: white;\n"
"    selection-background-color: #555;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(parent=self.centralwidget)
        self.webEngineView.setGeometry(QtCore.QRect(20, 20, 711, 491))
        self.webEngineView.setMinimumSize(QtCore.QSize(711, 0))
        self.webEngineView.setMaximumSize(QtCore.QSize(711, 16777215))
        self.webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView.setObjectName("webEngineView")
        self.FiltrosBarcos = QtWidgets.QComboBox(parent=self.centralwidget)
        self.FiltrosBarcos.setGeometry(QtCore.QRect(540, 70, 181, 26))
        self.FiltrosBarcos.setStyleSheet("QComboBox {\n"
"    background-color: #2b2b2b;\n"
"    color: white;\n"
"    border: 1px solid #555;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #2b2b2b;\n"
"    color: white;\n"
"    selection-background-color: #555;\n"
"}")
        self.FiltrosBarcos.setObjectName("FiltrosBarcos")
        self.FiltrosBarcos.addItem("")
        self.FiltrosBarcos.addItem("")
        self.FiltrosBarcos.addItem("")
        self.FiltrosBarcos.addItem("")
        self.FiltrosBarcos.addItem("")
        self.FiltrosBarcos.addItem("")
        self.FiltrosBarcos.addItem("")
        self.FiltrosBarcos.addItem("")
        self.FiltrosBarcos.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(230, 30, 191, 26))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #2b2b2b;\n"
"    color: white;\n"
"    border: 1px solid #555;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 30, 81, 26))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #2b2b2b;\n"
"    color: white;\n"
"    border: 1px solid #555;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #555;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.Busquedapaismmsi = QtWidgets.QComboBox(parent=self.centralwidget)
        self.Busquedapaismmsi.setGeometry(QtCore.QRect(130, 30, 89, 26))
        self.Busquedapaismmsi.setObjectName("Busquedapaismmsi")
        self.Busquedapaismmsi.addItem("")
        self.Filtro_site = QtWidgets.QComboBox(parent=self.centralwidget)
        self.Filtro_site.setGeometry(QtCore.QRect(540, 180, 181, 26))
        self.Filtro_site.setStyleSheet("QComboBox {\n"
"    background-color: #2b2b2b;\n"
"    color: white;\n"
"    border: 1px solid #555;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #2b2b2b;\n"
"    color: white;\n"
"    selection-background-color: #555;\n"
"}")
        self.Filtro_site.setObjectName("Filtro_site")
        self.Filtro_site.addItem("")
        self.Filtro_site.addItem("")
        self.Filtro_site.addItem("")
        self.Filtro_site.addItem("")
        self.Filtro_site.addItem("")
        self.Filtro_site.addItem("")
        self.Filtro_site.addItem("")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(540, 30, 181, 31))
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: #2b2b2b;\n"
"    color: white;\n"
"    border: 1px solid #555;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLabel::drop-down {\n"
"    border: none;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(540, 140, 181, 31))
        self.label_3.setStyleSheet("QLabel {\n"
"    background-color: #2b2b2b;\n"
"    color: white;\n"
"    border: 1px solid #555;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLabel::drop-down {\n"
"    border: none;\n"
"}")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FiltrosBarcos.setItemText(0, _translate("MainWindow", "Todos"))
        self.FiltrosBarcos.setItemText(1, _translate("MainWindow", "Pesca"))
        self.FiltrosBarcos.setItemText(2, _translate("MainWindow", "Remolque"))
        self.FiltrosBarcos.setItemText(3, _translate("MainWindow", "Velero"))
        self.FiltrosBarcos.setItemText(4, _translate("MainWindow", "Recreo"))
        self.FiltrosBarcos.setItemText(5, _translate("MainWindow", "Remolcador"))
        self.FiltrosBarcos.setItemText(6, _translate("MainWindow", "Pasajeros"))
        self.FiltrosBarcos.setItemText(7, _translate("MainWindow", "Carga"))
        self.FiltrosBarcos.setItemText(8, _translate("MainWindow", "Petrolero"))
        self.pushButton.setText(_translate("MainWindow", "Buscar"))
        self.Busquedapaismmsi.setItemText(0, _translate("MainWindow", "MMSI"))
        self.Filtro_site.setItemText(0, _translate("MainWindow", "Ninguna seleccionada"))
        self.Filtro_site.setItemText(1, _translate("MainWindow", "Mar Mediterraneo"))
        self.Filtro_site.setItemText(2, _translate("MainWindow", "Canal de Suez"))
        self.Filtro_site.setItemText(3, _translate("MainWindow", "Canal de Panamá"))
        self.Filtro_site.setItemText(4, _translate("MainWindow", "Estrecho de Malaka"))
        self.Filtro_site.setItemText(5, _translate("MainWindow", "Estrecho de Ormuz"))
        self.Filtro_site.setItemText(6, _translate("MainWindow", "Mar de China"))
        self.label_2.setText(_translate("MainWindow", "Tipo de barco:"))
        self.label_3.setText(_translate("MainWindow", "Localizaciones importantes:"))
from PyQt6 import QtWebEngineWidgets
